WITH NEWTAB AS(
SELECT BST.N,COUNT(B.P) AS CNT
FROM BST
LEFT JOIN BST AS B
ON B.P=BST.N
GROUP BY BST.N
)


SELECT NEWTAB.N,
CASE
    WHEN NEWTAB.CNT=0 THEN 'Leaf'
    WHEN BST.P IS NULL THEN 'Root'
    ELSE 'Inner'
END AS TYPE
FROM NEWTAB
JOIN BST ON BST.N=NEWTAB.N
ORDER BY NEWTAB.N
