SELECT S1.NAME
FROM STUDENTS S1
JOIN FRIENDS F1
ON S1.ID=F1.ID
JOIN PACKAGES P1
ON S1.ID = P1.ID
JOIN PACKAGES P2
ON P2.ID=F1.FRIEND_ID
WHERE P1.SALARY<P2.SALARY
ORDER BY P2.SALARY


WITH FIRST AS(
    SELECT STUDENTS.NAME AS NAME,STUDENTS.ID AS ID,PACKAGES.SALARY AS SALARY
    FROM STUDENTS
    JOIN PACKAGES
    ON STUDENTS.ID = PACKAGES.ID
),
NEWX AS(
    SELECT FIRST.ID AS ID,FIRST.NAME AS NAME,FRIENDS.FRIEND_ID AS FRIID,FIRST.SALARY AS SALARY
    FROM FIRST
    JOIN FRIENDS
    ON FIRST.ID = FRIENDS.ID
),
EXTRA AS(
    SELECT NEWX.ID AS ID,NEWX.NAME AS NAME,NEWX.FRIID AS FRIID,NEWX.SALARY AS SALARY,PACKAGES.SALARY AS FRISALARY
    FROM NEWX
    JOIN PACKAGES
    ON NEWX.FRIID=PACKAGES.ID
)

SELECT EXTRA.NAME
FROM EXTRA
WHERE SALARY<FRISALARY
ORDER BY FRISALARY
