SELECT 
CASE
    WHEN GRADES.GRADE<8 THEN NULL
    ELSE STUDENTS.NAME
END,
GRADES.GRADE,STUDENTS.MARKS
FROM STUDENTS
JOIN GRADES
ON STUDENTS.MARKS>=GRADES.MIN_MARK AND STUDENTS.MARKS<=GRADES.MAX_MARK
ORDER BY 
         GRADES.GRADE DESC, 
         CASE
            WHEN GRADES.GRADE>=8 THEN STUDENTS.NAME
            ELSE STUDENTS.MARKS
         END ASC
               
