SELECT DISTINCT F1.X,F1.Y
FROM
    (SELECT X,Y,ROW_NUMBER() OVER() AS ROWNO FROM FUNCTIONS)
     AS F1 
JOIN
(SELECT X,Y,ROW_NUMBER() OVER() AS ROWNO FROM FUNCTIONS)
     AS F2 
ON F1.X = F2.Y and F1.Y = F2.X and F1.ROWNO != F2.ROWNO
WHERE F1.X<=F1.Y
ORDER BY F1.X
